class Command:
    HELLO = "hello"
    CLOSE = "close"
    EXIT = "exit"
    ADD = "add"
    INVALID = "invalid"
    CHANGE = "change"
    FIND = "find"
    ALL = "all"
    FIND_NOTES = "find-notes"
    BIRTHDAYS = "birthdays"
    DELETE = "delete"
    HELP = "help"
